version: "3"

services:
  mariadb:
      build: ./mariadb
      container_name: inception_mariadb
      environment:
          - MARIADB_USER=${MARIADB_USER}
          - MARIADB_PASSWORD=${MARIADB_PASSWORD}
          - MARIADB_DATABASE=${MARIADB_DATABASE}
          - MARIADB_PORT=${MARIADB_PORT}
          - MARIADB_NEW_PWD=${MARIADB_NEW_PWD}
      volumes:
          - mariadb-volume:/var/lib/mysql
      image : mariadb
      expose:
          - "3306"
      networks:
          - intra
      tty: true
      restart: on-failure
#-------------------------------------------------------------------------------#
  nginx:
      build: ./nginx
      container_name: inception_nginx
      volumes:
          - wordpress-volume:/var/www/html
      ports:
          - "443:443"
      networks:
          - intra
      tty: true
      restart: on-failure
#-------------------------------------------------------------------------------#
  wordpress:
      depends_on:
         - mariadb
      build: ./wordpress
      container_name: inception_wordpress
      image: wordpress
      volumes:
          - wordpress-volume:/var/www/html
      environment:
          - WP_URL=https://${DOMAIN_NAME}
          - WP_DATABASE=${WP_DATABASE}
          - WP_TITLE=${WP_TITLE}
          - WP_ADMIN_USER=${WP_ADMIN_USER}
          - WP_ADMIN_PWD=${WP_ADMIN_PWD}
          - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
          - WP_USER=${WP_USER}
          - WP_USER_PWD=${WP_USER_PWD}
          - WP_USER_EMAIL=${WP_USER_EMAIL}
          - MARIADB_USER=${MARIADB_USER}
          - MARIADB_PASSWORD=${MARIADB_PASSWORD}
          - MARIADB_DATABASE=${MARIADB_DATABASE}
          - MARIADB_PORT=${MARIADB_PORT}
          - MARIADB_NEW_PWD=${MARIADB_NEW_PWD}
      expose: 
          - "9000"
      networks:
          - intra
      tty: true
      restart: on-failure

volumes:
  mariadb-volume:
    driver: local
    driver_opts:
      type: none
      device: ${MARIADB_HOST_VOLUME_PATH}
      o: bind
  wordpress-volume:
    driver: local
    driver_opts:
      type: none
      device: ${WP_HOST_VOLUME_PATH}
      o: bind

networks:
  intra:
      driver: bridge  